# Generated by Django 4.1.1 on 2024-04-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mymodel',
            table='model',
        ),
    ]
