# Generated by Django 4.1.1 on 2024-04-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_mymodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'stdent',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
